# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo
  - function_parameter_count

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

included:
  - ../SwiftyBeaver-Destinations

excluded:
  - Carthage
  #- Pods

line_length:
  warning: 200
  error: 250
