# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode8.3
xcode_project: Example/SwiftyBeaver-Destinations.xcodeproj
before_script:
#If one of this failed we have error and all process is stopped
- cd Example
- pod install --repo-update

script:
# It's only one command who count for valid or not build session
- scan -s SwiftyBeaver-Destinations-Example

after_success:
# I have put this in after_success coz it's failed.
# It's failed coz Extra Module isn't include inside SubPodSpec
- cd ..
- pod lib lint --verbose
